name: Website Tracker

on:
  schedule:
    - cron: '0 * * * *' # تشغيل الكود في الدقيقة 0 من كل ساعة
  workflow_dispatch: # إضافة زر لتشغيل الكود يدوياً متى أردت

jobs:
  check-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Tracker
        run: python tracker.py
